### PR TITLE
fix: add log and archive message ingress for sync

### LINKED ISSUE #3131: bug:  add a path for waku sync to bypass the timestamp check of 'validate'
### Problem
A store node with sync enabled fails to archive the "missing" messages identified by the sync process, because their timestamps are too old.

### Impact
The store sync nodes indicate that they are synced, because the waku sync storage is updated, but the messages are never inserted into the DB. StoreQueryRequests will return no results.

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Run 2 store nodes with their own DB backends, one with relay enabled
2. Send a few relay message to the node which has it enabled.
3. Wait for the other node to sync
4. See that messages that are older than 20s at the time of syncing are not archived

### Expected behavior
It is expected for all messages identified by the store sync process to be required by the store node, should be archived. the timestamps of the messages are already filtered to be within the `store-sync-range` config

### Screenshots/logs
No error logs are produced for this issue

### nwaku version/commit hash
This was specifically seen on nwaku versions: v0.33.0-rc.0-13-gd8e6a5 and v0.33.0-44-gc5a825, but it would have been present since store sync was implemented.

### PR DESCRIPTION
**Pull request by SionoiS**
Closes #3131 & #3132

### CODE REVIEW

File: waku/waku_archive/archive.nim [hunk 1]
```diff
@@ -87,6 +87,12 @@ proc handleMessage*(
 ) {.async.} =
   self.validator(msg).isOkOr:
     waku_archive_errors.inc(labelValues = [error])
+    trace "failed to insert message",
+      hash_hash = computeMessageHash(pubsubTopic, msg).to0xHex(),
```
Comment (gabrielmer) [inline waku/waku_archive/archive.nim:91]: shouldn't it be `msg_hash` instead of `hash_hash`? especially for consistency with all the other logs in the codebase

same comment for the other logs added here

File: waku/waku_archive/archive.nim [hunk 2]
```diff
@@ -111,6 +117,33 @@ proc handleMessage*(
...
+    self: WakuArchive,
+    msgHash: WakuMessageHash,
+    pubsubTopic: PubsubTopic,
+    msg: WakuMessage,
+) {.async.} =
+  let insertStartTime = getTime().toUnixFloat()
+
+  (await self.driver.put(msgHash, pubsubTopic, msg)).isOkOr:
+    waku_archive_errors.inc(labelValues = [insertFailure])
+    trace "failed to insert message",
```
Comment (gabrielmer) [inline waku/waku_archive/archive.nim:130]: shouldn't we log the failures at `debug` or `error` level? or it's something that happens a lot?

**Review by gabrielmer — APPROVED** [review]
LGTM, thanks so much!

File: waku/waku_archive/archive.nim (hunk 1 above)
Comment (SionoiS) [reply waku/waku_archive/archive.nim:91]: good catch probably a copy-pasta mistake.

File: waku/waku_archive/archive.nim (hunk 2 above)
Comment (SionoiS) [reply waku/waku_archive/archive.nim:130]: yeah potentially a lot of messages so I went with trace.

**Review by darshankabariya — APPROVED** [review]
LGTM !
